### DISCUSSION TITLE
Passing environment variables to MCP servers

### DISCUSSION THREAD

**Discussion by rahuldave** [lastmile-ai/mcp-agent#284] [General]
I have the following server(config.yaml):

```yaml
mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    meilisearch:
      command: "uvx"
      args: ["-n", "meilisearch-mcp"]
```

the meilisearch mcp needs env vars for the melisearch master key and the URL:PORT at which the meilisearch server itself runs. I tried passing it as variables before the uvx as you would do in a script but that didnt work. Whats the right way to do this? I cant be the only one who has encountered this need...

To be precise, the variables are also not inhereited from the parent environment, ie the python server (fastapi) in which i am using the mcp_agent library.
