### ISSUE TITLE
Trouble configuring a custom MCP server

### ISSUE THREAD

**Issue by DuskSwan** [lastmile-ai/mcp-agent#248]
**Issue Description:**

I am trying to add a custom MCP server to my mcp-agent configuration, but the agent does not seem to detect it. The "Tools available" section in the logs is always empty.

**Configuration:**

I have seen the following default configuration in the examples, which works as expected:

```YAML
mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem"]
```

I tried to add my own custom server, which is a Python script, by modifying the configuration as follows:
```YAML
mcp:
  servers:
    time:
      transport: "stdio"
      command: "python"
      args: ["path/to/my_servers/Timetools.py"]
```

However, after launching the agent with this configuration, the logs show Tools available.
```
[INFO] 2025-06-05T15:50:14 mcp_agent.web_page_summary - Tools available:   
{                                                                                                                         
  "data": {                                                                                                                 
    "meta": null,                                                                                                          
     "nextCursor": null,                                                                                                     
    "tools": []                                                                                                           
  }                                                                                                                     
}  
```

**Question:**

Could you please provide guidance on the correct way to configure a custom MCP server written in Python? Is there a specific protocol or output format that my Python script needs to follow to be correctly discovered by the mcp-agent?

Any help or examples would be greatly appreciated!

**Comment by saqadri** [comment]
@DuskSwan thanks for reaching out! Can you please confirm if your custom server lists tools as a capability?

One of the things MCP-agent does is it checks the server capabilities before trying to call tools/list or tools/call

**Comment by DuskSwan** [comment]
> server lists tools as a capability

Thanks for your quick response! But sorry I'm not entirely sure I understand what you mean by "the server lists tools as a capability".

I'm new to this and built my server following the `fastmcp` document. My server implementation is quite simple, and it looks like this:

```python
from fastmcp import FastMCP

mcp = FastMCP("My MCP Server")

@mcp.tool
def greet(name: str) -> str:
    """Returns a greeting."""
    return f"Hello, {name}!"

if __name__ == "__main__":
    mcp.run()
```

Could you please clarify at which step the server is supposed to "list tools as a capability"?

If my example is too simplistic, could you perhaps point me to an example that demonstrates the correct way to implement this capability?

Thank you so much for your help!

**Comment by DuskSwan** [comment]
I've found the solution to the problem.

The issue was that my MCP server has its own dedicated virtual environment. Therefore, the `command` should not be a generic `python` but the absolute path to the interpreter within that specific environment.

The correct configuration is:

```yaml
mcp:
  servers:
    time:
      transport: "stdio"
      command: "/path/to/my/virtualenv/bin/python" # or path/to/env/python.exe on Windows
      args: ["path/to/my_servers/Timetools.py"]
```

With this change, the agent now correctly detects the server and its tools.

Although this problem is resolved, I believe more detailed official documentation would be very helpful for future users to avoid this kind of issue.
