### ISSUE TITLE
Help: tavily mcp server support

### ISSUE THREAD

**Issue by doncat99** [lastmile-ai/mcp-agent#36]
I am having trouble when trying to use tavily mcp server.

my yaml file is like:
```
$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  path: "./logs/mcp_agent.log"
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem"]
    tavily-mcp:
      command: "npx"
      args: ["-y", "tavily-mcp@0.1.3"]
      env:
        TAVILY_API_KEY: "XXX"
      

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  #  default_model: "o3-mini"
  default_model: "gpt-4o-mini"
```

the output said that Server tavily not found in registry.

"message":"Iteration 2: Tool call results: [{'role': 'tool', 'tool_call_id': 'call_zt7OED3d9v3QF4wrH9ASwHhh', 'content': [{'type': 'text', 'text': \"Error executing tool 'tavily-mcp-tavily-search': Server 'tavily' not found in registry.\"}]}, {'role': 'tool', 'tool_call_id': 'call_HRXFRjOMlOU3v12pexvMGRmR', 'content': [{'type': 'text', 'text': \"Error executing tool 'tavily-mcp-tavily-search': Server 'tavily' not found in registry.\"}]}, {'role': 'tool', 'tool_call_id': 'call_oR2Dtr6kjqIJCCWncaPZElmZ', 'content': [{'type': 'text', 'text': \"Error executing tool 'tavily-mcp-tavily-search': Server 'tavily' not found in registry.\"}]}, {'role': 'tool', 'tool_call_id': 'call_EmWcNe9OhHPE0HY8I4pZzGP3', 'content': [{'type': 'text', 'text': \"Error executing tool 'tavily-mcp-tavily-search': Server 'tavily' not found in registry.\"}]}, {'role': 'tool', 'tool_call_id': 'call_HNfGub07K2So3DdasiYjgIXX', 'content': [{'type': 'text', 'text': \"Error executing tool 'tavily-mcp-tavily-search': Server 'tavily' not found in registry.\"}]}]"}

I am familiar with LangChain tools and new to MCP, would anyone be able to help me out?

**Comment by doncat99** [comment]
Problem solved.

1. the name of the server should not be "tavily-mcp", but "tavily". Not as the official [Tavily](https://github.com/tavily-ai/tavily-mcp) told me to. 

2. the env variable should be put into a secret YAML file as the Openai key does. The Wired thing is that the **NAME** of openai key is "api_key" but not "OPENAI_API_KEY", whereas the Name of Tavily key should be the one exactly with "TAVILY_API_KEY". The rule is wired. The solution is found on Issue, but not the readme file. I think the readme file should cover how to set env as well. 

```
openai:
  api_key: XXX
  base_url: XXX

anthropic:
  api_key: anthropic_api_key

tavily:
  TAVILY_API_KEY: XXX
```

**Comment by saqadri** [comment]
> Problem solved.
> 
> 1. the name of the server should not be "tavily-mcp", but "tavily". Not as the official [Tavily](https://github.com/tavily-ai/tavily-mcp) told me to.
> 2. the env variable should be put into a secret YAML file as the Openai key does. The Wired thing is that the **NAME** of openai key is "api_key" but not "OPENAI_API_KEY", whereas the Name of Tavily key should be the one exactly with "TAVILY_API_KEY". The rule is wired. The solution is found on Issue, but not the readme file. I think the readme file should cover how to set env as well.
> 
> ```
> openai:
>   api_key: XXX
>   base_url: XXX
> 
> anthropic:
>   api_key: anthropic_api_key
> 
> tavily:
>   TAVILY_API_KEY: XXX
> ```

@doncat99 can you try following the example for the slack MCP server here: https://github.com/lastmile-ai/mcp-agent/blob/main/examples/mcp_basic_slack_agent/mcp_agent.config.yaml#L9-L11

Basically you should be able to define the `TAVILY_API_KEY` in the `env` property in `mcp_agent.config.yaml` or `mcp_agent.secrets.yaml`.

```
mcp:
  servers:
    tavily-mcp:
      command: "npx"
      args: ["-y", "tavily-mcp@0.1.2"]
      env:
        "TAVILY_API_KEY": "your-api-key-here"
```

You can call the server `tavily` or `tavily-mcp`, as long as you are consistent when using that same name in the agent when referencing the server.

Please let me know if this works.

> I know we could construct a config structure and send it into config, but would it be more convenient for the project itself to read the .env file instead of creating a new extra secret YAML file?

I think this is fair, though it could be a security issue to load all environment variables. I use the same environment variable logic that the base MCP package does: https://github.com/lastmile-ai/mcp-agent/blob/73af711bd48d057eae01660baf4c4cd613e13c38/src/mcp_agent/mcp/mcp_connection_manager.py#L220
