### ISSUE TITLE
support for remote mcp servers

### ISSUE THREAD

**Issue by rkreddyp** [lastmile-ai/mcp-agent#41]
hello is there support for remote mcp servers with /sse ?

**Comment by saqadri** [comment]
> hello is there support for remote mcp servers with /sse ?

@rkreddyp there is! I would love for you to contribute an example using a remote MCP server. All that's needed is updating the `mcp_agent.config.yaml` server with a `url` and `transport: "sse"`:

https://github.com/lastmile-ai/mcp-agent/blob/main/examples/mcp_basic_agent/mcp_agent.config.yaml#L11

something like this:
```
mcp:
  servers:
    remote-mcp:
      transport: "sse"
      url: "https://..."
```

Full configuration possibilities: https://github.com/lastmile-ai/mcp-agent/blob/main/src/mcp_agent/config.py#L69
